name: Docker Image CI

on:
  push:
    branches:
      - '**'  # This matches all branches
  pull_request:
    branches:
      - '**'  # This matches all branches

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Get variables
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: env.DOCKERHUB_USERNAME != '' && env.DOCKER_PASSWORD != ''
      uses: docker/login-action@v3
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        context: .
        push: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        tags: |
          fajyz/runpod-worker-comfy:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
        cache-from: type=registry,ref=fajyz/runpod-worker-comfy:buildcache
        cache-to: type=registry,ref=fajyz/runpod-worker-comfy:buildcache,mode=max
